<a href="https://colab.research.google.com/github/YonDraco/learn-deep-learning/blob/main/BuildingDLSolutionsWithPyTorch/1_Foundations%20of%20PyTorch/demo6_AutogradWithVariables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch 

from torch.autograd import Variable

#### We create a Variable with Float tensor

The return value is not a variable instead it is a tensor

In [ ]:
var = Variable(torch.FloatTensor([9]))
var

tensor([9.])

In [ ]:
var.requires_grad

False

In [ ]:
var.requires_grad_()

tensor([9.], requires_grad=True)

#### We create two weight variables with gradients enabled

In [ ]:
w1 = Variable(torch.FloatTensor([3]), requires_grad = True)
w2 = Variable(torch.FloatTensor([7]), requires_grad = True)

In [ ]:
w1

tensor([3.], requires_grad=True)

In [ ]:
w2

tensor([7.], requires_grad=True)

#### We create two more variables using the weights

In [ ]:
result_var = var * w1

result_var 

tensor([27.], grad_fn=<MulBackward0>)

#### New variables derive enabled gradients from weights

In [ ]:
result_var.requires_grad

True

In [ ]:
result_var.backward()

In [ ]:
w1.grad

tensor([18.])

In [ ]:
w2.grad

In [ ]:
var.grad

tensor([6.])