<a href="https://colab.research.google.com/github/YonDraco/learn-deep-learning/blob/main/BuildingDLSolutionsWithPyTorch/1_Foundations%20of%20PyTorch/demo11_TensorflowDynamicComputationGraphs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

import tensorflow as tf

In [ ]:
tf.enable_eager_execution()

In [ ]:
tf.executing_eagerly() 

True

#### Only variable and constants are compatible with eager execution 

In [ ]:
W = tf.Variable(6, name = 'var_W')

x = tf.constant([10, 10], name = 'x')

b = tf.Variable(3, name = 'constant_b')

In [ ]:
W

<tf.Variable 'var_W:0' shape=() dtype=int32, numpy=6>

In [ ]:
x

<tf.Tensor: id=64, shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
b

<tf.Variable 'constant_b:0' shape=() dtype=int32, numpy=3>

In [ ]:
y = W * x + b

In [ ]:
y

<tf.Tensor: id=80, shape=(2,), dtype=int32, numpy=array([63, 63], dtype=int32)>

In [ ]:
print(y)

tf.Tensor([63 63], shape=(2,), dtype=int32)


In [ ]:
print(W*x)

tf.Tensor([60 60], shape=(2,), dtype=int32)


https://www.tensorflow.org/guide/eager#work_with_graphs

In [ ]:
np_result = np.multiply(W, x)

np_result

array([<tf.Tensor: id=108, shape=(), dtype=int32, numpy=60>,
       <tf.Tensor: id=111, shape=(), dtype=int32, numpy=60>], dtype=object)

In [ ]:
W.numpy()

6

In [ ]:
y.numpy()

array([63, 63], dtype=int32)