<a href="https://colab.research.google.com/github/YonDraco/learn-deep-learning/blob/main/BuildingDLSolutionsWithPyTorch/1_Foundations%20of%20PyTorch/demo3_ConversionsBetweenPyTorchAndNumPy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Interoperablity between Numpy arrays and Pytorch Tensors

In [1]:
import numpy as np
import torch

#### Converting tensor to numpy arrays

In [2]:
tensor = torch.rand(4, 3)
tensor

tensor([[0.0226, 0.0424, 0.6834],
        [0.1253, 0.8022, 0.1720],
        [0.0105, 0.6426, 0.7742],
        [0.2299, 0.7604, 0.5829]])

In [3]:
type(tensor)

torch.Tensor

### The numpy arrays use the same memory as the PyTorch tensor

In [4]:
numpy_from_tensor = tensor.numpy()                   
numpy_from_tensor

array([[0.02256334, 0.04238117, 0.6833691 ],
       [0.12533575, 0.80221164, 0.17198539],
       [0.01045156, 0.6426219 , 0.7741825 ],
       [0.22990537, 0.76041925, 0.582936  ]], dtype=float32)

In [5]:
type(numpy_from_tensor)

numpy.ndarray

In [6]:
torch.is_tensor(tensor)

True

In [7]:
torch.is_tensor(numpy_from_tensor)

False

#### The NumPy array and the Torch tensor share memory

In [8]:
numpy_from_tensor[0, 0] = 100.0

numpy_from_tensor

array([[1.0000000e+02, 4.2381167e-02, 6.8336910e-01],
       [1.2533575e-01, 8.0221164e-01, 1.7198539e-01],
       [1.0451555e-02, 6.4262187e-01, 7.7418250e-01],
       [2.2990537e-01, 7.6041925e-01, 5.8293599e-01]], dtype=float32)

In [9]:
tensor

tensor([[1.0000e+02, 4.2381e-02, 6.8337e-01],
        [1.2534e-01, 8.0221e-01, 1.7199e-01],
        [1.0452e-02, 6.4262e-01, 7.7418e-01],
        [2.2991e-01, 7.6042e-01, 5.8294e-01]])

#### Converting a numpy array to a Tensor

In [10]:
numpy_arr = np.array([[1.0, 2.0, 3.0], 
                      [10.0, 20.0, 30.0],
                      [100.0, 200.0, 300.0]])

numpy_arr

array([[  1.,   2.,   3.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [14]:
tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [16]:
torch.is_tensor(tensor_from_numpy)

True

#### The Numpy arrays and Tensor share the same memory
The tensor and numpy_from_tensor are shallow copies and share the same memory as the original numpy array. Modifying the original array affects the values of both tensor and numpy_from_tensor

In [17]:
tensor_from_numpy[0] = 1
tensor_from_numpy

tensor([[  1.,   1.,   1.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [18]:
numpy_arr

array([[  1.,   1.,   1.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

#### Convert the data into a torch.Tensor. 

If the data is already a Tensor with the same dtype and device, no copy will be performed, otherwise a new Tensor will be returned

In [19]:
np_array_one = np.array([4, 8])
np_array_one

array([4, 8])

In [20]:
tensor_from_array_one = torch.as_tensor(np_array_one)
tensor_from_array_one

tensor([4, 8])

In [21]:
np_array_one[1] = 5
np_array_one

array([4, 5])

In [22]:
tensor_from_array_one

tensor([4, 5])

#### torch.tensor() reads out the data from whatever it is passed, and constructs a leaf variable

In [23]:
np_array_two = np.array([2, 2])
np_array_two

array([2, 2])

In [24]:
tensor_from_array_two = torch.tensor(np_array_two)

tensor_from_array_two

tensor([2, 2])

#### in this method the tensor and array do not share memory

In [25]:
np_array_two[1] = 4
np_array_two

array([2, 4])

In [26]:
tensor_from_array_two

tensor([2, 2])