<a href="https://colab.research.google.com/github/YonDraco/learn-deep-learning/blob/main/BuildingDLSolutionsWithPyTorch/1_Foundations%20of%20PyTorch/demo2_PytorchTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

1.9.0+cu102


#### Get the current default floating point torch.dtype

In [2]:
torch.get_default_dtype()

torch.float32

#### default dtype for a tensor can only be a float type

#### The default floating point dtype is initially torch.float32
#### Set the default floating point to torch.float64

In [5]:
torch.get_default_dtype()

torch.float32

In [6]:
torch.set_default_dtype(torch.float64)

In [7]:
torch.get_default_dtype()

torch.float64

#### Creating Tensors

#### A Tensor initialized with a specific array, the torch tensor always creates a copy of the data

In [15]:
tensor_arr = torch.Tensor([[1,2,3], [4,5,6]])

In [16]:
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [17]:
torch.is_tensor(tensor_arr)

True

#### numel() returns the number of elements in a tensor

In [18]:
# In ra so phan tu trong mot tensor
torch.numel(tensor_arr)

6

#### An un-initialized Tensor of shape 2X2 allocated space in memory

In [19]:
tensor_uninitialized = torch.Tensor(2, 2) 

In [20]:
tensor_uninitialized

tensor([[4.6827e-310, 2.1008e-312],
        [9.7612e-313, 2.4827e-312]])

#### A tensor of size 2x2 initialized with random values

In [21]:
tensor_initialized = torch.rand(2, 2)

In [22]:
tensor_initialized

tensor([[0.0476, 0.2072],
        [0.8175, 0.4214]])

#### Tensors can be set to have specific data types

In [23]:
tensor_int = torch.tensor([5, 3]).type(torch.IntTensor) 
tensor_int

tensor([5, 3], dtype=torch.int32)

#### A Tensor of type short

In [24]:
tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])   
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

#### A Tensor of type float half (float16)

In [25]:
tensor_float = torch.tensor([1.0, 2.0, 3.0]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

#### A tensor filled with a specific values


In [26]:
tensor_fill = torch.full((2, 6), fill_value=10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

#### A tensor of size (2,4) containing all ones

In [27]:
tensor_of_ones = torch.ones([2, 4], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

#### A tensor of size (2,4) like tensor_of_ones containing all zeroes

In [28]:
tensor_of_zeroes = torch.zeros_like(tensor_of_ones)
tensor_of_zeroes

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

#### Create an identity 5X5 tensor

In [29]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

#### Get the list of indices of non-zero elements in a tensor
[ i, j ] index for non-zero elements

In [30]:
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

#### Create a sparse tensor using coordinates specified by indices and values

In [31]:
i = torch.tensor([[0, 1, 1],
                  [2, 2, 0]])

In [32]:
v = torch.tensor([3, 4, 5], dtype=torch.float32)

In [33]:
sparse_tensor = torch.sparse_coo_tensor(i, v, [2, 5])

In [34]:
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

## Inplace / Out-of-place
The first difference is that ALL operations on the tensor that operate in-place on it will have an "\_" postfix. For example, add is the out-of-place version, and add\_ is the in-place version.

#### .fill_ is in-place operation and it doesnt have any out-place equivalent

In [35]:
initial_tensor = torch.rand(2, 3) 
initial_tensor

tensor([[0.2512, 0.0743, 0.4134],
        [0.5682, 0.1114, 0.4955]])

In [36]:
initial_tensor.fill_(10) 

tensor([[10., 10., 10.],
        [10., 10., 10.]])

#### The add() method does an out-of-place add operation and returns a new tensor
This is assigned to the new_tensor variable

In [37]:
new_tensor = initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

#### The original tensor is unchanged

In [38]:
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

#### The add\_ method does an in-place add, changing the calling tensor

In [39]:
initial_tensor.add_(8)
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

#### The new_tensor was a separate copy and is unaffected

In [40]:
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

#### In-place version of sqrt()

In [41]:
new_tensor.sqrt_()
new_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

### Indexing, Slicing, Joining, Mutating Ops

#### Slicing

In [42]:
x = torch.linspace(start=0.1, end=10.0, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

#### Splits a tensor into a specific number of chunks.
- tensor (Tensor) – the tensor to split
- chunks (int) – number of chunks to return
- dim (int) – dimension along which to split the tensor


In [43]:
tensor_chunk = torch.chunk(x, 3, 0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

#### Concatenates the  sequence of tensors along the given dimension

All tensors must either have the same shape (except in the concatenating dimension) or be empty.

In [44]:
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3.0, 4.0, 5.0])

torch.cat((tensor1, tensor2, tensor3), 0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [45]:
random_tensor = torch.Tensor([[10, 8, 30], [40, 5, 6], [12, 2, 21]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [48]:
random_tensor[0, 1]

tensor(8.)

In [49]:
# Truy cập tất cả các hàng từ hàng 1 trở đi và các cột từ cột 1 trở đi
random_tensor[1:, 1:]

tensor([[ 5.,  6.],
        [ 2., 21.]])

#### Splits the tensor into chunks

In [51]:
random_tensor_split = torch.split(random_tensor, 2)
random_tensor_split

(tensor([[10.,  8., 30.],
         [40.,  5.,  6.]]), tensor([[12.,  2., 21.]]))

#### View

In [58]:
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [59]:
random_tensor.size()

torch.Size([3, 3])

In [60]:
resized_tensor = random_tensor.view(9)  
resized_tensor

tensor([10.,  8., 30., 40.,  5.,  6., 12.,  2., 21.])

In [ ]:
resized_tensor = random_tensor.view(-1, 6)  
resized_tensor

In [62]:
resized_tensor.size()

torch.Size([9])

#### view() does not create a deep copy - just a view as the name suggests
Modifying the original tensor affects the resized_tensor as they both point to the same space in memory

In [63]:
random_tensor[2, 2] = 100.0
resized_tensor

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])

#### Unsqueeze
Returns a new tensor with a dimension of size one inserted at the specified position.

In [64]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [65]:
random_tensor.shape

torch.Size([3, 3])

In [66]:
tensor_unsqueeze = torch.unsqueeze(random_tensor, 2)
tensor_unsqueeze

tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

In [67]:
tensor_unsqueeze.shape

torch.Size([3, 3, 1])

#### Transpose

#### Returns a tensor that is a transposed version of input. The given dimensions dim0 and dim1 are swapped.

In [68]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [69]:
tensor_transpose = torch.transpose(initial_tensor, 0, 1)
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

#### Sorting tensors
Tensors can be sorted along a specified dimension. If no dimension is specified, the last dimension is picked by default

In [70]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [71]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)

In [72]:
sorted_tensor

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])

In [73]:
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

# Math Operations
Pytorch supports a number of mathematical operations which can be performed on tensors. We take a look at a few of them here

In [74]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000], dtype=torch.float32)

#### Absolute values

In [75]:
tensor_abs = torch.abs(tensor_float)      
tensor_abs

tensor([1.1000, 2.2000, 3.3000], dtype=torch.float32)

In [76]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [77]:
new_tensor = torch.add(initial_tensor, 2)
new_tensor

tensor([[20., 20., 20.],
        [20., 20., 20.]])

In [78]:
torch.add(initial_tensor, 10, new_tensor)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: This overload of add is deprecated:
	add(Tensor input, Number alpha, Tensor other, *, Tensor out)
Consider using one of the following signatures instead:
	add(Tensor input, Tensor other, *, Number alpha, Tensor out) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:1025.)
  """Entry point for launching an IPython kernel.


tensor([[218., 218., 218.],
        [218., 218., 218.]])

In [79]:
rand1 = torch.abs(torch.randn(2, 3))
rand2 = torch.abs(torch.randn(2, 3))

In [80]:
add1 = rand1 + rand2
add1

tensor([[0.8311, 0.9119, 0.8745],
        [1.3568, 2.2477, 1.2692]])

#### The add() method does an out-of-place add operation and returns a new tensor
This is assigned to the new_tensor variable

In [81]:
add2 = torch.add(rand1, rand2)
add2

tensor([[0.8311, 0.9119, 0.8745],
        [1.3568, 2.2477, 1.2692]])

In [82]:
tensor = torch.Tensor([[-1, -2, -3],
                       [ 1,  2,  3]])

#### Element-wise division
The div() and mul() functions can be used to divide and multiply the values in a tensor. Here, we do an element-wise division between two tensors

In [83]:
tensor_div = torch.div(tensor, tensor + 0.3)
tensor_div

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]])

#### Element-wise multiplicaton

In [84]:
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]])

#### Clamp the value of a Tensor
There will be occasions where you would like to set upper and lower limits for the values in a tensor. This is where the clamp function is used. The value of an element is set to:
* min if if x<sub>i</sub> < min
* x<sub>i</sub> if min < x<sub>i</sub> < max
* max if x<sub>i</sub> > max

In [85]:
tensor_clamp = torch.clamp(tensor, min= -0.2, max=2)
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

## Vector Multiplication 

#### Dot product

In [86]:
t1 = torch.Tensor([1, 2])
t2 = torch.Tensor([10, 20])

In [ ]:
dot_product = torch.dot(t1, t2) 
dot_product

tensor(50.)

#### Matrix Vector product
If mat is a (n×m) tensor, vec is a 1-D tensor of size m, out will be 1-D of size n.

In [87]:
matrix = torch.Tensor([[1, 2, 3],
                       [4, 5, 6]])

vector = torch.Tensor([0, 1, 2])

In [88]:
matrix_vector = torch.mv(matrix, vector)
matrix_vector

tensor([ 8., 17.])

#### Matrix multiplication

In [89]:
another_matrix = torch.Tensor([[10, 30],
                               [20, 0],
                               [0 , 50]])

In [90]:
matrix_mul = torch.mm(matrix, another_matrix)
matrix_mul

tensor([[ 50., 180.],
        [140., 420.]])

#### Returns the indices of the maximum values of a tensor across a dimension.

In [91]:
torch.argmax(matrix_mul, dim=1)

tensor([1, 1])

In [92]:
torch.argmin(matrix_mul, dim=1)

tensor([0, 0])