<a href="https://colab.research.google.com/github/YonDraco/learn-deep-learning/blob/main/BuildingDLSolutionsWithPyTorch/1_Foundations%20of%20PyTorch/demo4_CUDASemantics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
torch.cuda.is_available()

True

In [4]:
# Initialize PyTorch’s CUDA state. You may need to call this explicitly if you are interacting 
# with PyTorch via its C API

torch.cuda.init()

In [5]:
torch.cuda.current_device()

0

In [6]:
torch.cuda.device_count()

1

In [7]:
torch.cuda.memory_allocated()

0

In [8]:
torch.cuda.memory_cached()

/usr/local/lib/python3.7/dist-packages/torch/cuda/memory.py:375: FutureWarning: torch.cuda.memory_cached has been renamed to torch.cuda.memory_reserved
  FutureWarning)


0

In [9]:
cuda = torch.device('cuda')

cuda

device(type='cuda')

In [10]:
cuda0 = torch.device('cuda:0')
cuda1 = torch.device('cuda:1')
cuda2 = torch.device('cuda:2')

In [11]:
cuda0, cuda1, cuda2

(device(type='cuda', index=0),
 device(type='cuda', index=1),
 device(type='cuda', index=2))

In [12]:
x = torch.tensor([10., 20.])

x

tensor([10., 20.])

In [13]:
x_default = torch.tensor([10., 20.], device=cuda)

x_default

tensor([10., 20.], device='cuda:0')

In [14]:
x0 = torch.tensor([10., 20.], device=cuda0)

x0

tensor([10., 20.], device='cuda:0')

In [16]:
x1 = torch.tensor([10., 20.], device=cuda0)

x1

tensor([10., 20.], device='cuda:0')

### Returns a copy of this object in CUDA memory.

If this object is already in CUDA memory and on the correct device, then no copy is performed and the original object is returned.

In [17]:
# Transferring a tensor from CPU to GPU 0
y = x.cuda()

y

tensor([10., 20.], device='cuda:0')

In [18]:
# Transferring a tensor from GPU 1 to GPU 0
y0 = x1.cuda()

y0

tensor([10., 20.], device='cuda:0')

In [21]:
print('Outside with context: ', torch.cuda.current_device())

with torch.cuda.device(0):
    
    print('Inside with context: ', torch.cuda.current_device())

print('Outside with context again: ', torch.cuda.current_device())

Outside with context:  0
Inside with context:  0
Outside with context again:  0


In [20]:
with torch.cuda.device(1):
    
    a = torch.tensor([10., 20.])
    
    a0 = torch.tensor([10., 20.], device=cuda0)
    
    a1 = torch.tensor([10., 20.], device=cuda)

RuntimeError: ignored

In [ ]:
a

tensor([10., 20.])

In [ ]:
a0

tensor([10., 20.], device='cuda:0')

In [ ]:
a1

tensor([10., 20.], device='cuda:1')

In [ ]:
b1 = a0.to(device=cuda1)

b1

tensor([10., 20.], device='cuda:1')

In [ ]:
sum_a = a + a0

RuntimeError: expected type torch.FloatTensor but got torch.cuda.FloatTensor

In [ ]:
sum_a = a1 + a0

RuntimeError: binary_op(): expected both inputs to be on same device, but input a is on cuda:1 and input b is on cuda:0

In [ ]:
sum_ax = a1 + x1

sum_ax

tensor([20., 40.], device='cuda:1')

In [ ]:
torch.cuda.memory_allocated()

9728

In [ ]:
torch.cuda.memory_cached()

1048576

In [ ]:
torch.cuda.empty_cache()

In [ ]:
torch.cuda.memory_cached()

1048576

### torch.Tensor.new_* functions preserve the type and the device of the original tensor

In [ ]:
preserve_context = x.new_full([2, 2], fill_value=1.1)

preserve_context

tensor([[1.1000, 1.1000],
        [1.1000, 1.1000]])

In [ ]:
preserve_context0 = x0.new_full([2, 2], fill_value=1.1)

preserve_context0

tensor([[1.1000, 1.1000],
        [1.1000, 1.1000]], device='cuda:0')

In [ ]:
preserve_context1 = x1.new_full([2, 2], fill_value=1.1)

preserve_context1

tensor([[1.1000, 1.1000],
        [1.1000, 1.1000]], device='cuda:1')